name: asp
channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - geopandas
  - descartes
  - shapely
  - contextily
  - pip
  - pip:
    - gdal
  # - "--editable=git+https://github.com/friedrichknuth/asp_ba_eval.git#egg=asp_ba_eval"