name: asp
channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - geopandas
  - descartes
  - shapely
  - contextily
  - xmltodict
  - pip
  - pip:
    - gdal
    - elevation
  # - "--editable=git+https://github.com/friedrichknuth/bare.git#egg=bare"